### ISSUE TITLE
Event Study Plot with not-yet-treated

### ISSUE THREAD

**Issue by frederickluser** [kylebutts/did2s#13]
Hey Kyle,

thanks for your great work. Very helpful. A quick question: Will it be possible in the nearer future to use the event-study function with only not-yet-treated units? That would be very helpful.

Best,
Frederic

**Comment by kylebutts** [comment]
Hi Frederick -- I thought about doing this, but some of these estimators do not work with not-yet-treated units (e.g. Sun and Abraham) and others require choices about estimation. Therefore, I'm not comfortable setting defaults for these. I could be persuaded to, but at the moment there's no option in the near future planned

**Comment by frederickluser** [comment]
I see, thanks for the feedback.

**Comment by frederickluser** [comment]
Dear Kyle, can I ask a quick follow-up question?
I'm confused, which estimators can be used with not-yet-treated units only. I'm asking because the fact that the code runs and produces results, doesn't necessarily mean that doing so is a valid approach, I guess…
For sure, Roth and Sant'Anna as well as Callaway and Sant'Anna should work properly, right? Gardner and Borusyak, Jaravel, and Spiess should also be valid, right?

Thanks for any input.

**Comment by kylebutts** [comment]
Callaway and Sant'Anna is the only package that allows this explicitly. If you run an estimator on a sample where everyone eventually gets treated, it depends on the code what happens. 

For example, in {did2s}, it would drop the time periods where all units are treated (since these periods would not have time fixed-effects estimated). If you have never-treated units in your sample, those will be included, so you're better off manually dropping them.

**Comment by frederickluser** [comment]
Thanks!
