### ISSUE TITLE
Fixed Intercept of Zero and Implications for Interpretation

### ISSUE THREAD

**Issue by kdmaclean** [kylebutts/did2s#33]
This is perhaps more of an interpretation question but throughout the documentation, i( ... , ref=...) is used to estimate effects _relative to_ the reference category, as with a traditional dummy variable. However, surprisingly, it will happily estimate _both_ effects FALSE and TRUE if you drop the reference category.

```
static <- did2s(df_het, 
                yname = "dep_var", first_stage = ~ 0 | state + year, 
                second_stage = ~i(treat), treatment = "treat", 
                cluster_var = "state")
fixest::esttable(static)
```
  
![image](https://github.com/kylebutts/did2s/assets/94643469/ea54fd90-2f57-4e6a-afe4-57cda60c7a37)

This is occuring because the second stage call is forcing the intercept to be zero. 

```fixest::feols(fixest::xpd(~ 0 + ..second_stage, lhs = yname)```

That is fine but the interpretation, I don't think, is what is being suggested. For instance, let's say we reverse the reference category and set the reference category to be TRUE. We would expect, that not treated observations are now -2.15 or so, relative to TRUE. But that isn't what occurs due to the zero intercept.

```
static <- did2s(df_het, 
                yname = "dep_var", first_stage = ~ 0 | state + year, 
                second_stage = ~i(treat,ref="TRUE"), treatment = "treat", 
                cluster_var = "state")
fixest::esttable(static)
```

![image](https://github.com/kylebutts/did2s/assets/94643469/80a66292-6027-404b-9c6a-58c4042bb0ed)

This seems to me to be more important in event studies. The coefficients don't actually change when a certain reference period is left out and it's not clear to me how it can be claimed that they are "relative" to the reference period if so. Whether I do 
```second_stage = ~ i(rel_year,ref=c(20)) ```

or 

```second_stage = ~ i(rel_year,ref=c(-1)```

the coefficients are identical (and thus, not relative to the left out category). Am I correct on this? I am probably missing something obvious though in the interpretation!

**Comment by kylebutts** [comment]
Hi @kdmaclean,

I thought I had fixed the docs ages ago; but clearly not. The example README should not be using `-1` as a reference value. It is a bit confusing and my intuition led me astray too when I was first writing this package.

What the second_stage is doing is summarizing $y_{it} - \hat{y}_{it}(0)$ where $\hat{y}$ is the fitted value from the first-stage. So when you regress that on a set of event-time dummy variables, you are just taking averages of $y_{it} - \hat{y}_{it}(0)$ for different sets. No need to omit any. The reason you do in TWFE estimated via OLS is because they are collinear with unit and time fixed effects. 

You can just not average for -1 and it won't affect anything because again there is no reference category. But you should not do that and plot a 0 estimate for -1 because that's not accurate. 

Hope that clarifies and I have updated the README examples.
